import type { CostEstimate } from "./costs";

/**
 * Helpers for FLUX.2 on Cloudflare Workers AI. Pure, so they can be unit
 * tested. Pricing is from the Workers AI pricing page (verified 2026-09-27,
 * see docs/API_PROVIDERS.md); the free plan includes 10,000 neurons per day,
 * which these list-price estimates do not subtract.
 */

export const FLUX_PRICING_SOURCE = "https://developers.cloudflare.com/workers-ai/platform/pricing/";
export const USD_PER_1000_NEURONS = 0.011;
export const FREE_NEURONS_PER_DAY = 10_000;

const MIN_EDGE = 256;
const MAX_EDGE = 1920;
/** Output area for "1K": 768×1024 at 3:4 keeps the cost at four 512² tiles. */
const BASE_AREA = 768 * 1024;

function roundTo16(value: number): number {
  return Math.max(16, Math.round(value / 16) * 16);
}

/** Output width/height for an aspect ratio ("3:4") and size ("1K" | "2K" | "4K"). */
export function fluxDimensions(aspectRatio: string, imageSize: string): { width: number; height: number } {
  const match = /^(\d+):(\d+)$/.exec(aspectRatio);
  const ratio = match ? Number(match[1]) / Number(match[2]) : 3 / 4;
  const area = imageSize === "1K" ? BASE_AREA : BASE_AREA * 4;
  let width = Math.sqrt(area * ratio);
  let height = width / ratio;
  // Fit into the model's 256–1920 range while keeping the ratio.
  const shrink = Math.min(1, MAX_EDGE / Math.max(width, height));
  width *= shrink;
  height *= shrink;
  const grow = Math.max(1, MIN_EDGE / Math.min(width, height));
  width = Math.min(MAX_EDGE, width * grow);
  height = Math.min(MAX_EDGE, height * grow);
  return { width: roundTo16(width), height: roundTo16(height) };
}

function tiles(size: { width: number; height: number }): number {
  return Math.ceil(size.width / 512) * Math.ceil(size.height / 512);
}

function megapixels(size: { width: number; height: number }): number {
  return (size.width * size.height) / (1024 * 1024);
}

/** Neurons for one generation, or null for models without a known formula. */
export function estimateFluxNeurons(
  model: string,
  output: { width: number; height: number },
  inputs: { width: number; height: number }[],
): number | null {
  if (model.endsWith("flux-2-klein-4b")) {
    return 26.05 * tiles(output) + inputs.reduce((sum, i) => sum + 5.37 * tiles(i), 0);
  }
  if (model.endsWith("flux-2-klein-9b")) {
    const extraMp = Math.max(0, Math.ceil(megapixels(output) - 1));
    const inputMp = inputs.reduce((sum, i) => sum + Math.ceil(megapixels(i)), 0);
    return 1363.64 + 181.82 * extraMp + 181.82 * inputMp;
  }
  return null;
}

export function fluxCost(model: string, output: { width: number; height: number }, inputs: { width: number; height: number }[]): CostEstimate {
  const neurons = estimateFluxNeurons(model, output, inputs);
  if (neurons == null) return { amount: null, currency: "USD", source: "unknown", pricingRef: null };
  return {
    amount: Math.round((neurons / 1000) * USD_PER_1000_NEURONS * 1e6) / 1e6,
    currency: "USD",
    source: "estimated",
    pricingRef: `${FLUX_PRICING_SOURCE} (list price; ${FREE_NEURONS_PER_DAY} neurons/day free)`,
  };
}

export interface CloudflareErrorBody {
  success?: boolean;
  errors?: { code?: number; message?: string }[];
}

/** Map a Workers AI error response to a queue error class and code. */
export function classifyCloudflareError(
  status: number,
  body: CloudflareErrorBody | null,
): { classification: "transient" | "permanent"; code: string; message: string } {
  const message = body?.errors?.map((e) => [e.code, e.message].filter(Boolean).join(": ")).join("; ") || `HTTP ${status}`;
  if (/daily free allocation|neurons? (limit|quota)|upgrade to .*workers paid/i.test(message)) {
    return { classification: "permanent", code: "provider_daily_quota", message };
  }
  if (/nsfw|unsafe|safety|content policy/i.test(message)) {
    return { classification: "permanent", code: "safety_filtered", message };
  }
  if (status === 429 || status === 408 || status >= 500) {
    return { classification: "transient", code: `http_${status}`, message };
  }
  return { classification: "permanent", code: `http_${status}`, message };
}

/** Detect the image format of generated bytes. */
export function sniffImageMime(data: Uint8Array): string {
  if (data[0] === 0x89 && data[1] === 0x50 && data[2] === 0x4e && data[3] === 0x47) return "image/png";
  if (data[0] === 0xff && data[1] === 0xd8) return "image/jpeg";
  if (data[0] === 0x52 && data[1] === 0x49 && data[2] === 0x46 && data[3] === 0x46 && data[8] === 0x57 && data[9] === 0x45) return "image/webp";
  return "application/octet-stream";
}
